### ISSUE TITLE
getting false on dd and null for api variables and endpoints

### ISSUE THREAD

**Issue by Thomasosho** [dnsimmons/openweather#11]
false
```
use Dnsimmons\OpenWeather\OpenWeather;

$weather = new OpenWeather();
        $current = $weather->getCurrentWeatherByPostal('900101');
        dd($current);
```

.env
```
OPENWEATHER_API_KEY="my api"
OPENWEATHER_API_LANG="en"
OPENWEATHER_API_DATE_FORMAT="m/d/Y"
OPENWEATHER_API_TIME_FORMAT="h:i A"
OPENWEATHER_API_DAY_FORMAT="l"
```

**Comment by dnsimmons** [comment]
This is the expected behavior when the request fails.
In the latest release logging has been added so please check your log file for an error.  

Since you have null config values ...
If your API values are coming up null I might suspect that you need to refresh your config cache. 

`php artisan config:cache`

Let me know if this helps.
